name: presensi_karyawan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  location: ^6.0.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_maps: ^26.1.35

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png

fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/outfit_regular.ttf
      - asset: assets/fonts/outfit_semibold.ttf
